// apps/api/src/lib/fnol-template.ts
import { InterviewTemplate } from './interviews-workflow';

export const FNOL_TEMPLATE: InterviewTemplate = {
  templateId: 'fnol-v1',
  name: 'First Notice of Loss (FNOL)',
  description: 'Comprehensive interview for capturing initial loss information',
  version: '1.0',
  sections: [
    {
      id: 'customer-info',
      title: 'Customer Information',
      description: 'Basic information about the policyholder',
      order: 1,
      questions: [
        {
          id: 'customer-name',
          type: 'short_text',
          label: 'Customer Name',
          required: true,
          validation: { min: 2, max: 100 },
          metadata: { mapping: 'customer.name' },
        },
        {
          id: 'customer-phone',
          type: 'short_text',
          label: 'Phone Number',
          required: true,
          validation: { pattern: '^\\+?[1-9]\\d{1,14}$' },
          metadata: { mapping: 'customer.phone' },
        },
        {
          id: 'customer-email',
          type: 'short_text',
          label: 'Email Address',
          required: true,
          validation: { pattern: '^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$' },
          metadata: { mapping: 'customer.email' },
        },
        {
          id: 'customer-address',
          type: 'long_text',
          label: 'Mailing Address',
          required: false,
          metadata: { mapping: 'customer.address' },
        },
      ],
    },
    {
      id: 'property-info',
      title: 'Property Information',
      description: 'Details about the damaged property',
      order: 2,
      questions: [
        {
          id: 'property-address',
          type: 'long_text',
          label: 'Property Address',
          required: true,
          metadata: { mapping: 'property.address' },
        },
        {
          id: 'property-type',
          type: 'multiple_choice',
          label: 'Property Type',
          required: true,
          options: ['Single Family Home', 'Multi-Family', 'Commercial', 'Industrial', 'Other'],
          metadata: { mapping: 'property.type' },
        },
        {
          id: 'property-year-built',
          type: 'number',
          label: 'Year Built',
          required: false,
          validation: { min: 1800, max: new Date().getFullYear() },
          metadata: { mapping: 'property.yearBuilt' },
        },
        {
          id: 'property-square-footage',
          type: 'number',
          label: 'Square Footage',
          required: false,
          validation: { min: 100, max: 100000 },
          metadata: { mapping: 'property.squareFootage' },
        },
        {
          id: 'property-occupancy',
          type: 'multiple_choice',
          label: 'Occupancy Status',
          required: true,
          options: ['Owner Occupied', 'Renter Occupied', 'Vacant', 'Under Construction'],
          metadata: { mapping: 'property.occupancy' },
        },
      ],
    },
    {
      id: 'insurance-info',
      title: 'Insurance Information',
      description: 'Insurance policy details',
      order: 3,
      questions: [
        {
          id: 'insurance-company',
          type: 'short_text',
          label: 'Insurance Company',
          required: true,
          metadata: { mapping: 'claim.insuranceCompany' },
        },
        {
          id: 'policy-number',
          type: 'short_text',
          label: 'Policy Number',
          required: true,
          metadata: { mapping: 'claim.policyNumber' },
        },
        {
          id: 'policy-effective-date',
          type: 'date',
          label: 'Policy Effective Date',
          required: false,
          metadata: { mapping: 'claim.policyEffectiveDate' },
        },
        {
          id: 'deductible',
          type: 'currency',
          label: 'Deductible Amount',
          required: false,
          validation: { min: 0 },
          metadata: { mapping: 'claim.deductible' },
        },
      ],
    },
    {
      id: 'loss-details',
      title: 'Loss Details',
      description: 'Information about the loss event',
      order: 4,
      questions: [
        {
          id: 'date-of-loss',
          type: 'date',
          label: 'Date of Loss',
          required: true,
          metadata: { mapping: 'claim.dateOfLoss' },
        },
        {
          id: 'time-of-loss',
          type: 'time',
          label: 'Time of Loss',
          required: false,
          metadata: { mapping: 'claim.timeOfLoss' },
        },
        {
          id: 'cause-of-loss',
          type: 'multiple_choice',
          label: 'Primary Cause of Loss',
          required: true,
          options: [
            'Wind / Hail',
            'Water Damage',
            'Fire',
            'Theft / Vandalism',
            'Lightning',
            'Tree Damage',
            'Structural Failure',
            'Other',
          ],
          metadata: { mapping: 'claim.causeOfLoss' },
        },
        {
          id: 'cause-description',
          type: 'long_text',
          label: 'Describe what happened',
          required: true,
          metadata: { mapping: 'claim.description' },
        },
      ],
    },
    {
      id: 'emergency-services',
      title: 'Emergency Services',
      description: 'First responders and emergency actions',
      order: 5,
      questions: [
        {
          id: 'fire-department-called',
          type: 'yes_no',
          label: 'Was the fire department called?',
          required: false,
          metadata: { mapping: 'claim.fireDepartmentCalled' },
        },
        {
          id: 'police-called',
          type: 'yes_no',
          label: 'Was the police called?',
          required: false,
          metadata: { mapping: 'claim.policeCalled' },
        },
        {
          id: 'emergency-services-details',
          type: 'long_text',
          label: 'Emergency services details',
          required: false,
          conditional: {
            dependsOn: 'fire-department-called',
            operator: 'equals',
            value: true,
          },
          metadata: { mapping: 'claim.emergencyServicesDetails' },
        },
      ],
    },
    {
      id: 'mitigation',
      title: 'Mitigation',
      description: 'Immediate actions taken to prevent further damage',
      order: 6,
      questions: [
        {
          id: 'mitigation-actions',
          type: 'multi_select',
          label: 'What mitigation actions were taken?',
          required: false,
          options: [
            'Tarp installed',
            'Water extraction',
            'Board up windows/doors',
            'Debris removal',
            'Electrical shut off',
            'Gas shut off',
            'Other',
          ],
          metadata: { mapping: 'claim.mitigationActions' },
        },
        {
          id: 'mitigation-company',
          type: 'short_text',
          label: 'Mitigation company (if applicable)',
          required: false,
          metadata: { mapping: 'claim.mitigationCompany' },
        },
      ],
    },
    {
      id: 'roof',
      title: 'Roof Damage',
      description: 'Assessment of roof damage',
      order: 7,
      questions: [
        {
          id: 'roof-damaged',
          type: 'yes_no',
          label: 'Is the roof damaged?',
          required: true,
          metadata: { mapping: 'claim.roofDamaged' },
        },
        {
          id: 'roof-type',
          type: 'multiple_choice',
          label: 'Roof type',
          required: false,
          conditional: {
            dependsOn: 'roof-damaged',
            operator: 'equals',
            value: true,
          },
          options: ['Asphalt Shingle', 'Metal', 'Tile', 'Flat', 'Wood Shake', 'Other'],
          metadata: { mapping: 'claim.roofType' },
        },
        {
          id: 'roof-age',
          type: 'number',
          label: 'Approximate roof age (years)',
          required: false,
          conditional: {
            dependsOn: 'roof-damaged',
            operator: 'equals',
            value: true,
          },
          validation: { min: 0, max: 100 },
          metadata: { mapping: 'claim.roofAge' },
        },
        {
          id: 'roof-description',
          type: 'long_text',
          label: 'Describe roof damage',
          required: false,
          conditional: {
            dependsOn: 'roof-damaged',
            operator: 'equals',
            value: true,
          },
          metadata: { mapping: 'claim.roofDescription' },
        },
      ],
    },
    {
      id: 'interior',
      title: 'Interior Damage',
      description: 'Assessment of interior damage',
      order: 8,
      questions: [
        {
          id: 'interior-affected-areas',
          type: 'multi_select',
          label: 'Which interior areas are affected?',
          required: false,
          options: [
            'Living Room',
            'Kitchen',
            'Bedrooms',
            'Bathrooms',
            'Basement',
            'Attic',
            'Garage',
            'Other',
          ],
          metadata: { mapping: 'claim.interiorAffectedAreas' },
        },
        {
          id: 'water-damage',
          type: 'yes_no',
          label: 'Is there water damage?',
          required: false,
          metadata: { mapping: 'claim.waterDamage' },
        },
        {
          id: 'mold-growth',
          type: 'yes_no',
          label: 'Is there visible mold growth?',
          required: false,
          metadata: { mapping: 'claim.moldGrowth' },
        },
        {
          id: 'interior-description',
          type: 'long_text',
          label: 'Describe interior damage',
          required: false,
          metadata: { mapping: 'claim.interiorDescription' },
        },
      ],
    },
    {
      id: 'exterior',
      title: 'Exterior Damage',
      description: 'Assessment of exterior damage',
      order: 9,
      questions: [
        {
          id: 'exterior-affected-areas',
          type: 'multi_select',
          label: 'Which exterior areas are affected?',
          required: false,
          options: [
            'Siding',
            'Windows',
            'Doors',
            'Gutters',
            'Fencing',
            'Deck/Patio',
            'Landscaping',
            'Other',
          ],
          metadata: { mapping: 'claim.exteriorAffectedAreas' },
        },
        {
          id: 'exterior-description',
          type: 'long_text',
          label: 'Describe exterior damage',
          required: false,
          metadata: { mapping: 'claim.exteriorDescription' },
        },
      ],
    },
    {
      id: 'photos',
      title: 'Photos',
      description: 'Photo documentation',
      order: 10,
      questions: [
        {
          id: 'photos-taken',
          type: 'yes_no',
          label: 'Have photos been taken?',
          required: false,
          metadata: { mapping: 'claim.photosTaken' },
        },
        {
          id: 'photo-count',
          type: 'number',
          label: 'How many photos?',
          required: false,
          conditional: {
            dependsOn: 'photos-taken',
            operator: 'equals',
            value: true,
          },
          validation: { min: 1 },
          metadata: { mapping: 'claim.photoCount' },
        },
        {
          id: 'photo-description',
          type: 'long_text',
          label: 'Describe what the photos show',
          required: false,
          conditional: {
            dependsOn: 'photos-taken',
            operator: 'equals',
            value: true,
          },
          metadata: { mapping: 'claim.photoDescription' },
        },
      ],
    },
    {
      id: 'documents',
      title: 'Documents',
      description: 'Related documentation',
      order: 11,
      questions: [
        {
          id: 'documents-available',
          type: 'multi_select',
          label: 'What documents are available?',
          required: false,
          options: [
            'Insurance policy',
            'Police report',
            'Fire report',
            'Estimates',
            'Invoices',
            'Receipts',
            'Other',
          ],
          metadata: { mapping: 'claim.availableDocuments' },
        },
      ],
    },
    {
      id: 'adjuster-info',
      title: 'Adjuster Information',
      description: 'Insurance adjuster details',
      order: 12,
      questions: [
        {
          id: 'adjuster-name',
          type: 'short_text',
          label: 'Adjuster Name',
          required: false,
          metadata: { mapping: 'adjuster.name' },
        },
        {
          id: 'adjuster-phone',
          type: 'short_text',
          label: 'Adjuster Phone',
          required: false,
          metadata: { mapping: 'adjuster.phone' },
        },
        {
          id: 'adjuster-email',
          type: 'short_text',
          label: 'Adjuster Email',
          required: false,
          metadata: { mapping: 'adjuster.email' },
        },
        {
          id: 'adjuster-company',
          type: 'short_text',
          label: 'Adjusting Company',
          required: false,
          metadata: { mapping: 'adjuster.company' },
        },
      ],
    },
    {
      id: 'special-notes',
      title: 'Special Notes',
      description: 'Additional important information',
      order: 13,
      questions: [
        {
          id: 'special-instructions',
          type: 'long_text',
          label: 'Any special instructions or notes?',
          required: false,
          metadata: { mapping: 'claim.specialNotes' },
        },
      ],
    },
    {
      id: 'additional-damage',
      title: 'Additional Damage',
      description: 'Any other damage not covered above',
      order: 14,
      questions: [
        {
          id: 'additional-damage-description',
          type: 'long_text',
          label: 'Describe any additional damage',
          required: false,
          metadata: { mapping: 'claim.additionalDamage' },
        },
      ],
    },
    {
      id: 'safety-concerns',
      title: 'Safety Concerns',
      description: 'Any safety hazards at the property',
      order: 15,
      questions: [
        {
          id: 'safety-hazards',
          type: 'multi_select',
          label: 'Are there any safety hazards?',
          required: false,
          options: [
            'Exposed electrical wiring',
            'Structural instability',
            'Water damage with electrical risk',
            'Mold exposure',
            'Chemical hazards',
            'Debris hazards',
            'None',
          ],
          metadata: { mapping: 'claim.safetyHazards' },
        },
        {
          id: 'safety-description',
          type: 'long_text',
          label: 'Describe safety concerns',
          required: false,
          metadata: { mapping: 'claim.safetyDescription' },
        },
      ],
    },
  ],
  settings: {
    autosave: true,
    autosaveInterval: 30,
    allowResume: true,
    allowEditAfterComplete: true,
    showProgress: true,
    showSectionNavigation: true,
  },
};
